baseURL = "https://godwin-blog.netlify.app/"
languageCode = 'en-us'
title = "Godwin's Blog"
theme = 'archie'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = false

paginate = 50 # articles per page

[params]
mode = "light"                                # color-mode → light,dark,toggle or auto
useCDN = false                                # don't use CDNs for fonts and icons, instead serve them locally.
font = "Inter"                                # Use Inter font everywhere.
subtitle = "Godwin's thoughts & observations"
mathjax = false                               # enable MathJax support
katex = false                                 # enable KaTeX support
favicon = "favicon.svg"

# Social Tags

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nav_devl/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Thoughts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Dumps"
url = "/tags"
weight = 4
